# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ppqgis
                                 A QGIS plugin
 Plugin to work with pandapower networks
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-23
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Fraunhofer IEE
        email                : mike.vogt@iee.fraunhofer.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import numpy

"""
    For Windows Users:
        this plugin requires geopandas, please make sure you have its dependencies (fiona) installed
        
"""
# TODO: Write a try for geopandas import and error out without crashing

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QListWidgetItem, QTreeWidgetItem
from qgis.core import QgsProject, QgsWkbTypes, QgsMessageLog, Qgis, NULL

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .pandapower_export_dialog import ppExportDialog
from .pandapower_runpp_dialog import ppRunDialog
from .pandapower_export_summary_dialog import ppExportSummaryDialog

# install requirements
import re
import sys
import pathlib
import os.path

from typing import List

# suppress a warning from the pyproj4 package
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)

# Requirement names handed to pip must be plain distribution names. Anything
# else in requirements.txt is rejected rather than passed to a subprocess.
DEPENDENCY_NAME_RE = re.compile(r'^[A-Za-z0-9][A-Za-z0-9._-]*$')

# The Browser panel tree (expanding a .json in the Browser) is disabled.
#
# Returning a Python subclass of QgsDataCollectionItem from
# QgsDataItemProvider.createDataItem() is not safe on QGIS 3.44: the method is
# declared /Factory/, and once QgsDirectoryItem has stored the returned pointer
# in its C++ child vector the Python half of the object is torn away. The item
# reverts to a plain QgsDataCollectionItem and QGIS crashes with an access
# violation or heap corruption as soon as the node is expanded or refreshed --
# the QgsBrowserModel::flags() -> hasDragEnabled() path.
#
# This reproduces with a ~40 line example that does not involve this plugin at
# all, and is unaffected by every ownership policy (sip.transferto, holding a
# Python reference, or neither), so it is a binding limitation rather than
# something this code can work around.
#
# Networks are opened through Layer > Data Source Manager > pandapower instead,
# which does not go through createDataItem() and is unaffected. The item classes
# are kept in the tree so the feature can be revived once the binding allows it.
ENABLE_BROWSER_TREE = False

class ppqgis:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale. The setting is absent on a fresh QGIS profile, so
        # it must not be sliced unconditionally.
        locale = QSettings().value('locale/userLocale') or ''
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'pandapower_qgis_{}.qm'.format(locale[0:2]))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&pandapower QGIS Plugin')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start_export = None
        self.first_start_runpp = None
        self.dlg_export = None
        self.dlg_runpp = None
        self.dlg_export_summary = None
        self.dir = None
        self.layer_id_dict = None
        # Browser providers. References are held here because the registries
        # take ownership on the C++ side (see register_browser_providers).
        self.data_item_provider = None
        self.data_item_gui_provider = None
        self.source_select_provider = None

    def installer_func(self):
        plugin_dir = os.path.dirname(os.path.realpath(__file__))

        import subprocess

        try:
            import pip
        except ImportError:
            QgsMessageLog.logMessage("pip missing, trying to install/update pip.",
                                     level=Qgis.MessageLevel.Info)
            # Bootstrap pip by running the bundled get-pip script in its own
            # interpreter process instead of exec()ing it into this one.
            get_pip = str(pathlib.Path(plugin_dir, 'scripts', 'get_pip.py'))
            subprocess.check_call([sys.executable, get_pip])
            import pip
            # just in case the included version is old
            subprocess.check_call([sys.executable, "-m", "pip", "install", "--upgrade", "pip"])

        sys.path.append(plugin_dir)

        with open(os.path.join(plugin_dir, 'requirements.txt'), "r") as requirements:
            for dep in requirements.readlines():
                # part string at any ==, ~=, <=, >=
                dep = re.split("[~=<>]=", dep.strip(), 1)[0]
                if not DEPENDENCY_NAME_RE.match(dep):
                    QgsMessageLog.logMessage("Skipping malformed requirement {!r}".format(dep),
                                             level=Qgis.MessageLevel.Warning)
                    continue
                try:
                    __import__(dep)
                    QgsMessageLog.logMessage("Trying to load {}".format(dep), level=Qgis.MessageLevel.Info)
                except ImportError:
                    QgsMessageLog.logMessage("{} not available, installing".format(dep),
                                             level=Qgis.MessageLevel.Warning)
                    subprocess.check_call([sys.executable, "-m", "pip", "install", "--", dep])

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('pandapower_qgis', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/pandapower_qgis/pp.svg'
        export_icon_path = ':/plugins/pandapower_qgis/pp_export.svg'
        runpp_icon_path = ':/plugins/pandapower_qgis/pp.svg'    # tmp

        self.add_action(
            icon_path=export_icon_path,
            text=self.tr(u'export to pandapower'),
            callback=self.exprt,
            parent=self.iface.mainWindow())

        # Note: there is no longer an "import" action. A pandapower network is
        # opened directly from the Browser panel or the Data Source Manager,
        # and edits are written back to the same file. See
        # docs/dataprovider_v2_plan.md.

        self.add_action(
            icon_path=runpp_icon_path,
            text=self.tr(u'run pandapower network'),
            callback=self.runpp_action,
            parent=self.iface.mainWindow())

        self.register_browser_providers()
        self.connect_unsaved_changes_prompt()

        # will be set False in run()
        self.first_start_export = True
        self.first_start_runpp = True

    def connect_unsaved_changes_prompt(self):
        """Warn about networks with uncommitted changes before the project closes.

        Edits live in the shared network until the layer's edit buffer is
        committed, so closing a project can otherwise discard them silently.
        """
        from qgis.core import QgsProject

        try:
            QgsProject.instance().cleared.connect(self.warn_about_unsaved_networks)
        except Exception as error:
            print('Could not connect project-cleared signal: {}'.format(error))

    def warn_about_unsaved_networks(self):
        """Tell the user which networks still hold unwritten changes."""
        from .network_session import NetworkSession

        dirty = [session for session in NetworkSession.all_sessions()
                 if session.dirty]
        if not dirty:
            return

        from qgis.PyQt.QtWidgets import QMessageBox

        paths = '\n'.join(session.path for session in dirty)
        QMessageBox.warning(
            self.iface.mainWindow() if self.iface else None,
            self.tr('Unsaved pandapower changes'),
            self.tr('These networks have changes that were never saved:\n\n'
                    '{}\n\nThe changes were not written to disk.').format(paths),
        )

    def register_browser_providers(self):
        """Register the Data Source Manager page, and optionally the Browser.

        The registry takes ownership of the provider on the C++ side, so a
        Python reference is kept as well: without it the object can be garbage
        collected while QGIS still holds a pointer to it.

        The Browser tree is **disabled**, see ENABLE_BROWSER_TREE.
        """
        from qgis.core import QgsApplication
        from qgis.gui import QgsGui
        from .pandapower_source_select import PandapowerSourceSelectProvider

        if ENABLE_BROWSER_TREE:
            from .pandapower_data_items import PandapowerDataItemProvider
            from .pandapower_data_item_gui import PandapowerDataItemGuiProvider

            self._register_browser_tree(
                PandapowerDataItemProvider, PandapowerDataItemGuiProvider)

        self.source_select_provider = PandapowerSourceSelectProvider()
        QgsGui.sourceSelectProviderRegistry().addProvider(
            self.source_select_provider)

    def _register_browser_tree(self, item_provider_cls, gui_provider_cls):
        """Register the experimental Browser tree providers.

        Args:
            item_provider_cls: The QgsDataItemProvider subclass.
            gui_provider_cls: The QgsDataItemGuiProvider subclass.
        """
        from qgis.core import QgsApplication
        from qgis.gui import QgsGui

        self.data_item_provider = item_provider_cls()
        QgsApplication.dataItemProviderRegistry().addProvider(
            self.data_item_provider)

        self.data_item_gui_provider = gui_provider_cls()
        QgsGui.dataItemGuiProviderRegistry().addProvider(
            self.data_item_gui_provider)

    def unregister_browser_providers(self):
        """Remove the Browser and Data Source Manager providers again.

        Must happen on unload, or reloading the plugin leaves QGIS holding
        pointers into a module that no longer exists.
        """
        from qgis.core import QgsApplication
        from qgis.gui import QgsGui

        if self.data_item_provider is not None:
            QgsApplication.dataItemProviderRegistry().removeProvider(
                self.data_item_provider)
            self.data_item_provider = None

        if self.data_item_gui_provider is not None:
            QgsGui.dataItemGuiProviderRegistry().removeProvider(
                self.data_item_gui_provider)
            self.data_item_gui_provider = None

        if self.source_select_provider is not None:
            QgsGui.sourceSelectProviderRegistry().removeProvider(
                self.source_select_provider)
            self.source_select_provider = None

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&pandapower QGIS Plugin'),
                action)
            self.iface.removeToolBarIcon(action)

        self.unregister_browser_providers()

        from qgis.core import QgsProject

        try:
            QgsProject.instance().cleared.disconnect(
                self.warn_about_unsaved_networks)
        except (TypeError, RuntimeError):
            pass  # Never connected, or already torn down

    def exprt(self):
        """Run method that performs all the real work"""
        """
        Information collected and displayed after export:
            amount bus
            amount lines
            amount lines using derived length
            amount lines containing errors
            used std_type's
        """

        from .ppqgis_export import power_network, pipes_network
        initial_run = False

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start_export:
            self.first_start_export = False
            self.dlg_export = ppExportDialog()
            self.dlg_export_summary = ppExportSummaryDialog()

        # get all layers
        layers = QgsProject.instance().mapLayers()

        tree_widget = self.dlg_export.layerTreeWidget

        # clear tree of all items
        tree_widget.clear()

        # Generate Tristate Group item for layers
        layer_item = QTreeWidgetItem(tree_widget)
        layer_item.setText(0, self.tr("layers"))
        layer_item.setFlags(layer_item.flags() | QtCore.Qt.ItemIsTristate | QtCore.Qt.ItemIsUserCheckable)
        layer_item.setExpanded(True)
        tree_widget.addTopLevelItem(layer_item)

        layer_lookup = {}

        for layer in layers:
            name = layers[layer].name()
            # add layer item with checkbox to treeWidget
            tree_item = QTreeWidgetItem(layer_item)
            tree_item.setText(0, name)
            tree_item.setFlags(tree_item.flags() | QtCore.Qt.ItemIsUserCheckable)
            tree_item.setCheckState(0, QtCore.Qt.CheckState.Checked)
            layer_item.addChild(tree_item)
            item_index = layer_item.indexOfChild(tree_item)

            # Make item name clickable. (as opposed to checkbox only)
            # If using itemClicked checkbox becomes unresponsive
            tree_widget.itemPressed.connect(
                lambda item: item.setCheckState(0,
                    QtCore.Qt.CheckState.Checked
                    if item.checkState(0) == QtCore.Qt.CheckState.Unchecked
                    else QtCore.Qt.CheckState.Unchecked
                )
            )

            layer_lookup[item_index] = layer

        # show the dialog
        self.dlg_export.show()
        # Run the dialog event loop
        result = self.dlg_export.exec_()
        # See if OK was pressed
        if result:
            # get selected layers
            selected_layers = list()
            for ind in range(layer_item.childCount()):
                if layer_item.child(ind).checkState(0) == QtCore.Qt.CheckState.Checked:
                    selected_layers.append(layer_lookup[ind])

            # self.installer_func()

            if self.dlg_export.power:
                power_network(self, selected_layers)
            else:
                pipes_network(self, selected_layers)




    def _active_pandapower_session(self):
        """Find the network session the power flow should run on.

        Prefers the layer selected in the Layers panel, and falls back to the
        first pandapower layer in the project.

        The session is read straight off the provider rather than being looked
        up by decoding ``layer.source()`` and matching the file path. The
        provider already holds the session it is using, so asking it directly
        cannot disagree with itself, while the decode-and-match route fails if
        the URI cannot be parsed or the path does not normalise to the same key
        (a UNC path, a mapped drive, or a symlinked directory all do this).

        Returns:
            NetworkSession or None: The session, or None if no pandapower layer
                is open.
        """
        candidates = []

        active = self.iface.activeLayer() if self.iface else None
        if active is not None:
            candidates.append(active)
        candidates.extend(QgsProject.instance().mapLayers().values())

        for layer in candidates:
            provider = getattr(layer, 'dataProvider', None)
            if provider is None:
                continue
            provider = layer.dataProvider()
            session = getattr(provider, 'session', None)
            if session is not None and session.net is not None:
                return session

        return None

    def _describe_missing_session(self):
        """Explain why no network could be found, for the message bar.

        A bare "no network" is unhelpful when layers are visibly open, so the
        message distinguishes an empty project from pandapower layers whose
        provider has no usable network behind it.

        Returns:
            str: A message naming the most likely cause.
        """
        layers = list(QgsProject.instance().mapLayers().values())
        pandapower_layers = [
            layer for layer in layers
            if getattr(layer.dataProvider(), 'name', lambda: '')()
            == 'PandapowerProvider'
        ]

        if not pandapower_layers:
            return ('Open a network first: '
                    'Layer > Data Source Manager > pandapower.')

        # Layers exist but none carries a live network. This means their
        # providers failed to load the file, e.g. it was moved or deleted after
        # the project was saved.
        names = ', '.join(layer.name() for layer in pandapower_layers[:3])
        return ('Found {} pandapower layer(s) ({}) but none has a loaded '
                'network. The network file may have been moved or deleted. '
                'Check the Python console for details.'.format(
                    len(pandapower_layers), names))

    def runpp_action(self):
        """Run runpp to run pandapower network"""
        from .ppqgis_runpp import run_network

        # Create the dialog (first time only)
        if self.first_start_runpp:
            self.first_start_runpp = False
            self.dlg_runpp = ppRunDialog()  # New dialog
        # Find the network to calculate: the active layer when it is a
        # pandapower one, otherwise the first pandapower layer in the project.
        session = self._active_pandapower_session()

        if session is None:
            self.iface.messageBar().pushMessage(
                "No pandapower network",
                self._describe_missing_session(),
                level=Qgis.Warning,
                duration=8
            )
            return

        # Set network info in the dialog
        self.dlg_runpp.setup_session(session)

        # Run dialog
        self.dlg_runpp.show()
        result = self.dlg_runpp.exec_()
